version: '3'
services:
  arangodb:
    platform: linux/x86_64
    image: arangodb:3.8.5
    ports:
      - "${ARANGO_PORT:-8529}:8529"
    environment:
      # - ARANGO_ROOT_PASSWORD=${ARANGO_PASSWORD:-letmein}
      - ARANGO_NO_AUTH=1
    volumes:
      - "${ARANGO_DATA:-./arangodb}:/var/lib/arangodb3"
      - "${ARANGO_DATA:-./arangodb}-apps:/var/lib/arangodb-apps"